### ISSUE TITLE
Open list of instances from instance switcher button

### ISSUE THREAD

**Issue by odinsdream** [DagAgren/toot#204]
If the user has the Accessibility setting called "Reachability" enabled, this setting can be accidentally triggered by trying to use the Account Switcher.

The Account Switcher is really conveniently placed and easy to use one-handed with a thumb, so for me it's a great accessibility improvement over other Mastodon clients like Tootdon. I would like to see it stay, but perhaps be adjusted in some way such that users who also rely on the Reachability iOS feature don't accidentally trigger it.

**Comment by DagAgren** [comment]
Considering doing some kind of long tap to pop up a list of instances or something similar.

**Comment by scottdwest** [comment]
When using any if the x like if phones I am cibstantkyr app switching instead of account switching.

**Comment by DagAgren** [comment]
Remember that you can swipe from anywhere on that button. You do not need to swipe from the bottom of it.

**Comment by JonahAragon** [comment]
I just want to chime in and agree with this issue, because on an iPhone X/XS this is super easy to trigger either reachability or just the swipe to home functionality since it’s so close to the home bar no matter where you swipe from. 

Long Press or 3D Touch on the button to pull up the list would be an excellent alternative method.

**Comment by DagAgren** [comment]
Added a long press popup menu.
