### ISSUE TITLE
Don’t tag user who boosted a toot when you reply

### ISSUE THREAD

**Issue by MichielBijl** [DagAgren/toot#276]
It would be nice if the user that boosted a toot wasn’t automatically tagged when you hit reply.

There’re a different opinions on this so maybe it could be an option?

Related thread: [Kaia and Zoë on boost-toot-reply-tags](https://queer.garden/web/statuses/101461002414619477)

**Comment by dg01d** [comment]
Definitely prefer to see this as configurable behaviour.

Just because someone has boosted a post into your timeline, doesn't mean you want to include them in your response. 

If they had something worthwhile to offer, then they could have responded, and if you wanted to respond to them, you could respond to their post.
