### ISSUE TITLE
URLs that include emojis aren‘t clickable

### ISSUE THREAD

**Issue by optikfluffel** [DagAgren/toot#370]
Example-URL: [🎄.rixx.de](https://🎄.rixx.de)

**Comment by DagAgren** [comment]
Turns out this is because Swift and iOS don't have built-in support for punycode, and implementing it myself would require some trickery that I am not entirely comfortable with in terms of ensuring it doesn't introduce any risky new bugs. So I think for now I am going to not fix this, since it's such an edge case.
