### ISSUE TITLE
crashes when using camera or picture on iOS 10

### ISSUE THREAD

**Issue by lewlepton** [DagAgren/toot#463]
as the title says.
I have an old iPhone, running iOS 10. but any time I want to use a picture or the camera to then use a picture, it crashes right away

thanks

**Comment by DagAgren** [comment]
iOS 10 is very badly supported at the moment. It is hard to test for, and has lots of weird behaviour that cause issues when developing, and I don't really have the time to keep testing and fixing everything on iOS 10, unfortunately. I've been considering raising the minimum requirement to at least 11 because I can't reasonably deal with 10, but I don't want to cut iOS 10 users off completely...

**Comment by lewlepton** [comment]
that is fair enough. more than fair enough, because of the age of the OS & keeping on top of a different workflow is just a bit too much work for not enough earned.
im trying to get a new phone, one that at least isn't going to be out of date too soon. so at least ill be able to enjoy it further with a better/updated iOS ;)
