### ISSUE TITLE
Re-order images before posting

### ISSUE THREAD

**Issue by nfagerlund** [DagAgren/toot#48]
Images seem to get attached to the toot in the order they finish uploading, which can mess up sequential images. 

It'd be good to check after the images finish and make sure the final toot matches the selection/preview order. Would also be nice to hold and drag to re-order images if I messed up on the initial selection order.

**Comment by DagAgren** [comment]
They are not supposed to, they are supposed to have a consistent ordering always, the same as the number labels in the picker. If that ever changes, that is a bug.

**Comment by nfagerlund** [comment]
cool. Should I try and come up with a test case? Consistency is the whole problem, but I bet I could rig something up by, e.g., putting two sub-kb pix after two multi-meg ones.

**Comment by DagAgren** [comment]
Would be good if you could reproduce it!

**Comment by nfagerlund** [comment]
Here's an example of this behavior: 

https://mastodon.social/@nfagerlund/100311797640481147

The description text shows the selection order. Notice that it behaves somewhat differently per app: 

- on web and pinafore and amaroq, images display in the finished-uploading order, full stop.
- on Toot, the thumbnail preview appears in the selection order, as desired. But if you expand the images and try to scroll through them, the linear order doesn't match the thumbnail order; it's the order shown in the other apps. So if you start with the first thumbnail, you bump into the end unexpectedly after the second image and have to backtrack.

**Comment by nfagerlund** [comment]
Two tiny and two normal seems to be a pretty reliable reproduction for this, btw.

**Comment by DagAgren** [comment]
Hmm, this is annoying.

First off, there was a simple bug: Toot! failed to put spaces in between the links it added to the toot, which meant it was showing images in the order they exist in the metadata. This is easily fixed, which makes Toot! now show the images in the correct order.

HOWEVER.

The images are still in the wrong order in the metadata, which is because apparently they are ordered by id rather than the same order that they were supplied when creating the toot. This means that the web interface will show them in a different order, as it uses the metadata order. And also Toot! uses the metadata order when showing the images full screen.

The only way to fix this as things stand now is to upload images one by one in order, which is annoying. Or maybe I need to check with @Gargron if this ordering is intended or not...

**Comment by Gargron** [comment]
@DagAgren For reference inserting shortcode into the text is not required anymore

Images are sorted by upload order due to the way the database schema was designed.

The default web app uploads as soon as you select a file, so there is no extra delay when posting. (The alt text and focal point can be updated on already uploaded files.) Of course that means you can't re-order with drag and drop.

**Comment by DagAgren** [comment]
I guess I'll make the uploader upload serially. It's slower, which is a shame, but having the images out of order is too annoying.

(I wish I had enough control over the HTTP stack to just upload everything in parallel and then hold off on the last packet to let the files finish in order...)

Also, that reminds me, what I also want to do is to make it possible to add the URLs manually inside the toot text, so you can have inline images. Toot! already supports displaying this nicely.

**Comment by DagAgren** [comment]
Ok, I think I've fixed it for now by making uploads sequential.
