### ISSUE TITLE
Long pressing links crashes application 

### ISSUE THREAD

**Issue by tonilampela** [DagAgren/toot#68]
(At least) On iOS 12 public beta Toot! (Build 24) crashes when long pressing links in toots.

**Comment by tonilampela** [comment]
Oddly enough I’m only able to reproduce this on iPad, not on iPhone.

**Comment by DagAgren** [comment]
Think this is the same as issue 69, it seems that showing an action sheet is crashing on iOS 12 for some mysterious reason. Been seeing this crash in the logs for a while now, so I don't think it's new in 24. It's good to have the exact steps to trigger it though!

Although since it is iOS 12 only, I think I will wait for another beta or two before bothering to do anything about it, it might just be an iOS 12 bug.

**Comment by edwellbrook** [comment]
If this is only happening on iPad it's likely because it's missing a sourceView + sourceRect as part of the popover presentation. Action sheets are displayed as a popover on iPads 😄

**Comment by tonilampela** [comment]
And this crashing is definitely still going on with the latest betas. I’m not sure if this happens on iOS 11 as I don’t have another iPad to test with... Let me know if I can provide any more information, but @edwellbrook thery sounds plausible as it is only occuring with action sheets..
